version-file = "pkg/version/version"

pre-commit = [
    "golangci-lint run",
    "husky lint-staged"
]
commit-msg = [
    "husky lint-commit"
]

[lint-staged]

"{pkg/,cmd/}{**/}*.go" = [
    "goimports -l -w"
]

"nodepkg/{**/}*{.ts,.tsx,.mjs,.js,.jsx.json}" = [
    "pnpx eslint --quiet"
]
