name: Go

on:
  push:
    branches:
      - "main"
    tags:
      - 'v*'
    paths:
      - cmd
      - pkg
      - go.mod
      - dagger.cue

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - run: curl -sSLf https://raw.githubusercontent.com/octohelm/dagger/main/install.sh | sudo sh

      - run: dagger do go ship pushx
        env:
          GH_USERNAME: ${{ github.actor }}
          GH_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          GIT_SHA: ${{ github.sha }}
          GIT_REF: ${{ github.ref }}
